language: node_js

node_js:
  - "12"

cache:
  directories:
    - "node_modules"

script: echo "Success!"

stages:
  - setup
  - sonar
  - deploy

jobs:
  include:
    - stage: setup
      script:
        - npm i
    - stage: sonar
      script:
        - sonar-scanner
      addons:
        sonarcloud:
          organization: "skaleb"
          token: "$SONAR_API_KEY"
    - stage: deploy
      deploy:
        provider: heroku
        api_key: "$HEROKU_API_KEY"
        app: "x-the-spot"
        skip_cleanup: true
